### ISSUE TITLE
Replace therubyracer with mini_racer to work on arm64

### ISSUE THREAD

**Issue by alex9434** [cenit-io/cenit#2808]
Is it possible to replace therubyracer with mini_racer? Unfortunately therubyracer does not compile on arm64 because it uses a very old version of libv8. mini_racer is faster and uses a newer version of libv8 that compiles on arm.

**Comment by macarci** [comment]
Carrying therubyracer has been a bit painful since it haven't been updated for many years but, unfortunately it's a dependency of another gem we use (handlebars) and both mini_racer and therubyracer can't coexist right now since they depend on differents versions of V8. A great solution would be to have a version of the handlebars gem using mini_racer instead therubyracer.
